---
name: On pull_request
on:
  pull_request:

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  pretendBuild:
    name: execute bnci build workflow
    uses: ./.github/workflows/pretend.yaml
    with:
      RELEASE: false
    secrets: inherit
